/** Auto-generated by preprocessing/generate_minimap.py — do not edit manually. */
export const MINIMAP_BOUNDS = {
  "west": -76.0,
  "east": -65.0,
  "south": -56.0,
  "north": -17.0
} as const;
export const MINIMAP_IMAGE = `${import.meta.env.BASE_URL}chile-dem.png`;
