name: Trigger production deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy isaiash.com with latest Horizon Lens
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: isaiash/isaiash-dev
          event-type: deploy-horizon
